### ISSUE TITLE
能否适配下f49c08ea566385db339c6628f65c3a121033f67c

### ISSUE THREAD

**Issue by qyh214** [Nekoer/mirai-plugins-novelai#2]
大佬能否适配下hash：f49c08ea566385db339c6628f65c3a121033f67c这个版本，因为这个版本有大佬提供了在a卡和i下使用cpu的能力；
还有这个等待api返回能否自定义，一般这种靠cpu的可能需要长达10-20分钟，超时需要设的久一点

**Comment by Nekoer** [comment]
超时时间已经默认10分钟了，要是这么长时间都没返回就别搞novelai了
hash昨天测试的时候最新版也能用

**Comment by qyh214** [comment]
啊，可以用；不过还是建议可以把超时作为单独的可选配置哦
